[tool.poetry]
name = "slipway"
version = "0.14.0"
description = "CLI tool for managing development containers"
authors = ["AGhost-7 <jonathan.boudreau.92@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
slipway = 'slipway:main'

[tool.poetry.dependencies]
python = "^3.7"
docker = "^4.0.0"
PyYAML = "^5.3"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
mypy = "^0.800"
bpython = "^0.21"
black = "^21.4b2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
