[tool.poetry]
name = "slipway"
version = "0.10.0"
description = "CLI tool for managing development containers"
authors = ["AGhost-7 <jonathan.boudreau.92@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
slipway = 'slipway:main'

[tool.poetry.dependencies]
python = "^3.6"
docker = ">=4.0.0"
PyYAML = "^5.3"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
